staff/staff/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('store/', include('store.urls')),
    # path('', include('store1.urls')), 
]

staff/store/urls.py
from django.urls import path

from . import views

app_name = 'store'
urlpatterns = [
    path('', views.menu, name='menu'),
    path('say-hello/', views.hello),
    path('staff-list/', views.staff_list, name='staff_list'),
    path('staff-details/<int:id>', views.staff_details, name='staff_details'),
]

staff/store/models.py
from django.db import models


class Category(models.Model):
    category = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.category}"
    
    class Meta:
        ordering = ["category"]
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Item(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")
    category_fk = models.ForeignKey(Category, on_delete=models.PROTECT, related_name="items", verbose_name="Категория")
    get_date = models.DateField(verbose_name="Дата появления")
    color = models.CharField(max_length=20, blank=True, null=True, verbose_name="Цвет")

    def __str__(self):
        return f"{self.name} / {self.category_fk.category}"
    
    class Meta:
        ordering = ["name"]
        verbose_name = "Вещь"
        verbose_name_plural = "Вещи"

staff/store/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Item


def hello(request):
    return HttpResponse("Hello")


def menu(request):
    template = "staff/index.html"
    context = {}
    return render(request=request, template_name=template, context=context)


def staff_list(request):
    # собрать данные из модели
    items = Item.objects.all()  # list[Item] - QuerySet
    # подключить html-шаблон
    template = "staff/staff_list.html"
    # создаем контекст - переменные шаблона
    context = {
        "t_title": "Список вещей",
        "t_items": items,
    }
    return render(request=request, template_name=template, context=context)


def staff_details(request, id):
    item = Item.objects.get(id=id)
    same_items = Item.objects.filter(category_fk=item.category_fk)
    template = "staff/staff_details.html"
    context = {
        "item": item,
        "t_items": same_items,
    }
    return render(request=request, template_name=template, context=context)

staff/templates/staff/index.html
<a href="{% url 'store:staff_list' %}">Список вещей</a>

staff/templates/staff/staff_details.html
<a href="{% url 'store:menu' %}">Меню</a><br />
<a href="{% url 'store:staff_list' %}">Список вещей</a>

<h1>{{ item.name }}</h1>
<h4>{{ item.category_fk.category }}</h4>
<p>{% if item.color %}{{ item.color }}{% endif %}</p>
<p>{{ item.get_date }}</p>

<hr />
<h4>Похожие вещи</h4>
<p>
    <table>
        <tr>
            <td>ID</td>
            <td>Категория</td>
            <td>Название</td>
            <td>Цвет</td>
            <td>Дата приобретения</td>
        </tr>
    {% for item in t_items %}
        <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.category_fk }}</td>
            <td><a href="{% url 'store:staff_details' item.id %}">{{ item.name }}</a></td>
            <td>{% if item.color %}{{ item.color }}{% endif %}</td>
            <td>{{ item.get_date }}</td>
        </tr>
    {% endfor %}
    
    </table>
</p>

staff/templates/staff/staff_list.html
<a href="{% url 'store:menu' %}">Меню</a>

<h1>{{ t_title }}</h1>

<ol>
{% for item in t_items %}
    <li>{{ item.name }} ({{ item.category_fk }}) - {{ item.get_date }} 
        
        {% if item.color %}
            [{{ item.color }}]
        {% endif %}

    </li>
{% endfor %}
</ol>

<table>
    <tr>
        <td>ID</td>
        <td>Категория</td>
        <td>Название</td>
        <td>Цвет</td>
        <td>Дата приобретения</td>
    </tr>
{% for item in t_items %}
    <tr>
        <td>{{ item.id }}</td>
        <td>{{ item.category_fk }}</td>
        <td><a href="{% url 'store:staff_details' item.id %}">{{ item.name }}</a></td>
        <td>{% if item.color %}{{ item.color }}{% endif %}</td>
        <td>{{ item.get_date }}</td>
    </tr>
{% endfor %}

</table>